### ISSUE TITLE
Any documentation or practical example ?

### ISSUE THREAD

**Issue by vincent-picaud** [tecosaur/Org.jl#16]
I would be more than happy to use this package, however I am stuck because I miss some examples/documentation.

Do these kinds of examples or documentation exist somewhere ?

A minimal example of what I want to do is as follows. I have an org doc like this:
```
#+title: my title
* Heading A
:PROPERTIES:
:CREATED:: 2022-08-17 14:06:05
:END:

Text 1

Text 2

|---+---+--------------|
| A | B | a,b,c        |
| 3 | 4 | u, [[id:2ff48db4-e652-4606-a692-7d29e4dea802][Composition Z]], v |

* Details
:PROPERTIES:
:CREATED:: 2022-08-17 14:26:15
:END:

** Composition Z
:PROPERTIES:
:CREATED:: 2022-08-17 14:26:56
:ID:       2ff48db4-e652-4606-a692-7d29e4dea802
:END:
a,b,c

```
I would like to:
1/ jump to headline "Heading A"
2/ parse its table to extract its components
3/ recognize the link "Composition Z" and jump to the associated headline
4/ parse the content of the "Composition Z" section (to retrieve the "a,b,c" string)

Can you tell me if your package is well suited for such task?

Thanks,
Vincent P

**Comment by tecosaur** [comment]
Documentation is currently a bit lacking, as are utilities for interacting with parsed documents. That said, you can currently do this:

```julia
doc = org"""
#+title: my title
* Heading A
:PROPERTIES:
:CREATED:: 2022-08-17 14:06:05
:END:

Text 1

Text 2

|---+---+--------------|
| A | B | a,b,c        |
| 3 | 4 | u, [[id:2ff48db4-e652-4606-a692-7d29e4dea802][Composition Z]], v |

* Details
:PROPERTIES:
:CREATED:: 2022-08-17 14:26:15
:END:

** Composition Z
:PROPERTIES:
:CREATED:: 2022-08-17 14:26:56
:ID:       2ff48db4-e652-4606-a692-7d29e4dea802
:END:
a,b,c
"""

table = filter(e -> e isa Org.Table, doc.headings[1].section.contents)[1]
cells = Iterators.flatten(getproperty.(filter(r -> r isa Org.TableRow, table.rows), :cells))
cellcontent = getproperty.(cells, :contents) |> Iterators.flatten |> collect

map(filter(o -> o isa Org.Link && o.path.protocol == "id", cellcontent)) do link
    id = link.path.path
    hindex = findfirst(h -> h["ID"] == id, doc.headings)
    if !isnothing(hindex)
        doc.headings[hindex].section.contents |> first |> string
    end
end
```

which gives

```
1-element Vector{String}:
 "a,b,c"
```

**Comment by vincent-picaud** [comment]
Thank you very much, I could not have written that from scratch.
From this starting point, I will try to fulfil my needs.

Just curious, are you using your package on a regular basis ? for which tasks ?

Org is the central Emacs package I use for my work. In the past, I tried to develop some tools to mix Julia & Org. Do not try to use them, they are now obsolete : 
- some tips to export org doc with Julia code: https://github.com/vincent-picaud/Project-Template-For-OrgMode
- an attempt to replace Documenter.jl. The idea was to generate org doc from Julia code: https://github.com/vincent-picaud/J4Org.jl

It looks like your package would be perfect for such kind of tools :)
