### ISSUE TITLE
Parser fails at src_LANG{expr} {{{results(=result=)}}}

### ISSUE THREAD

**Issue by schoettl** [tecosaur/Org.jl#17]
Hi @tecosaur, great work and thank you for all the fixes today!!
It's so impressing how fast it parses 14k lines of org.

The parser fails with an error in my org file line 14025 ;)

I don't actually use the parser, just want to contribute with bug reports if you don't mind.

```
org"src_R{1*1} {{{results(=1=)}}}"
```

This tripple {{{ }}} is inserted by org mode when evaluating the inline src with C-c C-c.

I mention this because this sample code is not in the test samples from the other issue.

**Comment by tecosaur** [comment]
This was a display issue, not a parse issue, and it is fixed in 7882dcd95a5dff474ff9c31b447f5aa481d4042d.
