### ISSUE TITLE
Parser fails at links which contains unescaped square brackets

### ISSUE THREAD

**Issue by schoettl** [tecosaur/Org.jl#18]
Example org:

```org
* foo [2023-01-28 Sa]
* bar
[[*foo \[2023-01-28 Sa\]][foo [2023-01-28 Sa]​]]
```

I generated this link with `org-store-link` on the first header and inserted it with `org-insert-link`.

```julia
julia> org"* foo [2023-01-28 Sa]
       * bar
       [[*foo \[2023-01-28 Sa\]][foo [2023-01-28 Sa]​]]
       "
```

Hm, I guess this is not an easy one to fix.

**Comment by tecosaur** [comment]
Fixed in 9500f25c293cdd993c755a42e46def6d241d4477.
