### ISSUE TITLE
parsetree gives MethodError

### ISSUE THREAD

**Issue by yantar92** [tecosaur/Org.jl#2]
I just tried

    text = parse(Org, "* This is a headline")
    parsetree(text)

The result is

    Org Parse Tree
    ERROR: MethodError: no method matching *(::Char, ::Vector{OrgMode.OrgObject})
    Closest candidates are:
      *(::Any, ::Any, ::Any, ::Any...) at operators.jl:560
      *(::Union{AbstractChar, AbstractString}, ::Union{AbstractChar, AbstractString}...) at strings/basic.jl:260
      *(::Union{SparseArrays.AbstractSparseMatrixCSC{TA, Ti}, SubArray{TA, 2, var"#s814", Tuple{Base.Slice{Base.OneTo{Int64}}, I}, L} where {I<:AbstractUnitRange, var"#s814"<:SparseArrays.AbstractSparseMatrixCSC{TA, Ti}, L}} where Ti, ::Union{StridedVector{T} where T, BitVector}) where TA at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/SparseArrays/src/linalg.jl:50
      ...
    Stacktrace:
      [1] *(::Char, ::Vector{OrgMode.OrgObject}, ::Char)
        @ Base ./operators.jl:560
      [2] parsetree(io::Base.TTY, h::OrgMode.Heading, maxdepth::Int64, depth::Int64)
        @ OrgMode /tmp/OrgMode.jl/src/analysis/parsetree.jl:36
      [3] _broadcast_getindex_evalf
        @ ./broadcast.jl:648 [inlined]
      [4] _broadcast_getindex
        @ ./broadcast.jl:621 [inlined]
      [5] getindex
        @ ./broadcast.jl:575 [inlined]
      [6] macro expansion
        @ ./broadcast.jl:984 [inlined]
      [7] macro expansion
        @ ./simdloop.jl:77 [inlined]
      [8] copyto!
        @ ./broadcast.jl:983 [inlined]
      [9] copyto!
        @ ./broadcast.jl:936 [inlined]
     [10] copy
        @ ./broadcast.jl:908 [inlined]
     [11] materialize
        @ ./broadcast.jl:883 [inlined]
     [12] parsetree(io::Base.TTY, org::Org, maxdepth::Int64, depth::Int64)
        @ OrgMode /tmp/OrgMode.jl/src/analysis/parsetree.jl:10
     [13] parsetree(io::Base.TTY, org::Org, maxdepth::Int64)
        @ OrgMode /tmp/OrgMode.jl/src/analysis/parsetree.jl:5
     [14] parsetree(org::Org, maxdepth::Int64) (repeats 2 times)
        @ OrgMode /tmp/OrgMode.jl/src/analysis/parsetree.jl:1
     [15] top-level scope
        @ REPL[21]:1

**Comment by tecosaur** [comment]
Ah, I forgot to update a bit of that code when I upgraded heading titles from strings to an array of `OrgObject`s. Thanks for catching that. Fixed in a405cbcd0ec60e779d048b15c81d97cd5d21b2a4
