### ISSUE TITLE
Headline with properties

### ISSUE THREAD

**Issue by yantar92** [tecosaur/Org.jl#3]
Another trial. The propery drawer is ignored.

    text = parse(Org, "* TODO [#A] This is a headline with tags, todo keyword, and priority, and properties :tag1:tag2:\n:PROPERTIES:\n:P1: 1\n:P2: 2\n:P2+: 3\n:END:\nParagraph")
    parsetree(text)
    
    Org Parse Tree
    Heading (This is a headline with tags, todo keyword, and priority, and properties)
        Section
            Paragraph
                TextPlain

**Comment by tecosaur** [comment]
Ah yep, that needs to be added. Property draw and planning support was a fairly recent addition. You can see that they're there if you either do `org(text)`, `print(text)`, or `dump(text)`. Before I start showing those attributes, I'm not sure if I should move those attributes from being a heading property to a section property though?

I wrote this just based off me reading https://orgmode.org/worg/dev/org-syntax.html which has,
> Property drawers are a special type of drawer containing properties attached to a headline. They are located right after a headline and its planning information. 

However, you seem to have a property draw at the start of your config, and that's reminded me that org-roam does too. So now I'm feeling less certain about how property drawers / planning should be treated.

**Comment by yantar92** [comment]
> Before I start showing those attributes, I'm not sure if I should move those attributes from being a heading property to a section property though?

In org-element, they always belong to heading property. Parsing the heading properties is one of the slower parts of `org-element-parse-buffer`:

    (headline (:raw-value "This is a headline with tags, todo keyword, and priority, and properties"
		:begin 1 :end 149 :pre-blank 0
        :contents-begin 98 :contents-end 149 :robust-begin 138 :robust-end 147
        :level 1 :priority 65 :tags ("tag1" "tag2") :todo-keyword "TODO"
        :todo-type todo :post-blank 0 :footnote-section-p nil
        :archivedp nil :commentedp nil :post-affiliated 1
        :P1 "1" :P2 "2" :P2+ "3"
        :title...)


> However, you seem to have a property draw at the start of your config, and that's reminded me that org-roam does too. So now I'm feeling less certain about how property drawers / planning should be treated.

That's a special case called document-wide property drawer. A relatively recent addition.

The parsing sequence is generally defined by `org-element--next-mode`:

    org-data
		section
			top-comment
            property-drawer
            ...

    headline
		section
			planning
			property-drawer
            ...

**Comment by tecosaur** [comment]
> That's a special case called document-wide property drawer. A relatively recent addition.

Ah, I don't think this is documented yet in the syntax page. Righteo. Thanks for the clarification and help with this 🙂

**Comment by tecosaur** [comment]
Oh, and I just added the missing output in f14a7467e22a9a855328be93ce49fcae8fe4b0d0. Document-wide property drawers are not *currently* supported.

**Comment by yantar92** [comment]
Confirmed
