### ISSUE TITLE
Render Description Lists as Definition Lists

### ISSUE THREAD

**Issue by kovariance** [tecosaur/Org.jl#4]
Org description lists should probably render as HTML defnition list. That is,

``` org
- key1 :: val1
- key2 :: val2
```
should render to

``` html 
<dl>
  <dt>key1</dt>
  <dd>val1</dd>
  <dt>key2</dt>
  <dd>val2</dd>
</dl>
```

Currently, it would render as an unordered list `<ul>...</ul>`.

**Comment by tecosaur** [comment]
This would be the correct behaviour, but do note that HTML export backend is *very* WIP.

**Comment by tecosaur** [comment]
Done.
