### ISSUE TITLE
Render to HTML AST

### ISSUE THREAD

**Issue by kovariance** [tecosaur/Org.jl#5]
Currently, the (in-progress) HTML renderer  outputs to a string (or, rather, to an IO buffer). It would be more convenient to render it to an HTML syntax tree structure. This would make it easier for the user to further modify the output without needlessly parsing the intermediate HTML. I think a good inspiration would be [unfiedjs](https://unifiedjs.com/)'s approach.

Though, _one_ potential issue would be supporting HTML export blocks, since that might require adding an HTML parser as a dependency.

**Comment by tecosaur** [comment]
Hmm, this sounds like a good idea but may be best as an add-on package.

I've tried to structure this in such a way that building alternative exporters should be quite straightforward.
