### ISSUE TITLE
How can I install and test this in Julia

### ISSUE THREAD

**Issue by schoettl** [tecosaur/Org.jl#9]
Sorry, for this Julia-noob question.

But how can I test this library? Is it already in the package registry so that `import Org.jl` just works? Or how can I run a Julia REPL and load the library?

**Comment by tecosaur** [comment]
You can `] add Org`, then call `using Org`. That's it. See https://github.com/tecosaur/Org.jl#basic-usage for examples of where you might go from there 🙂.

NB: It will take a few seconds the first time it does something, and be pretty speedy after that.

**Comment by schoettl** [comment]
OK, nice. Maybe that's worth to add to the README.

Strange, "Fetching:" in Julia hangs at 99.9 % since a few minutes with 100 % CPU. Is that normal?

Edit: Ah, now it's done!

**Comment by tecosaur** [comment]
The process is the exact same as with any other Julia package, so I'm not sure it's worth it.

**Comment by schoettl** [comment]
I mean because some people coming from Emacs/Org or Organice and don't kow Julia. But never mind.

**Comment by tecosaur** [comment]
Hmm, not a bad idea.
